---
- name: install packages
  apt:
    name: "{{ required_packages }}"
    update_cache: true
    state: present
    dpkg_options: 'force-confold'

- name: install pip
  easy_install:
    name: 'pip'
    state: present

- name: install pip requirements
  pip:
    name: "{{ pip_modules }}"
    state: present

- name: add required apt keys
  apt_key:
    data: "{{ lookup('file', item) }}"
    state: present
  with_items: "{{ repo_keys }}"

- name: add npms repo key
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    - 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'

- name: add required repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ repos }}"

- name: install custom packages
  apt:
    name: "{{ custom_packages }}"
    update_cache: true
    state: present
    dpkg_options: 'force-confold'

- name: create systemd directory
  file:
    path: '/etc/systemd/system/docker.service.d'
    recurse: true

- name: copy override.conf
  copy:
    src: 'docker.override.conf'
    dest: '/etc/systemd/system/docker.service.d/override.conf'
    mode: 0644
    owner: 'root'
    group: 'root'
  register: docker_service

- name: reload docker
  systemd:
    daemon_reload: true
  when:
    - docker_service.changed

- name: restart docker
  systemd:
    name: 'docker'
    state: restarted
  when:
    - docker_service.changed
