---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: vagrant-ubuntu
    box: bento/ubuntu-16.04
    memory: 512
    cpus: 1
provisioner:
  name: ansible
  lint:
    enabled: false
lint:
  enabled: false
verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    v: 1

